name: Build APK

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'  # ✅ Especifica versión

      - name: Install dependencies
        run: |
          flutter pub get
          flutter pub run flutter_launcher_icons:main  # ✅ Genera iconos

      - name: Build APK
        run: flutter build apk --release --verbose

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 30  # ✅ Guarda por 30 días